### ISSUE TITLE
gen2 2i4

### ISSUE THREAD

**Issue by duperray** [geoffreybennett/scarlett2#3]
it doesn't seems gen2 2i4 is supported.

any advice on how to:
show firmware version
update it?

cheers,

Pierre

**Comment by geoffreybennett** [comment]
Hi @duperray,

I don't think that it's possible to update the firmware in the 2nd Gen 2i4. See https://support.focusrite.com/hc/en-gb/articles/207547145-Mix-Control-or-Focusrite-Control-for-bus-powered-Scarletts and https://downloads.focusrite.com/focusrite/scarlett-2nd-gen/scarlett-2i4-2nd-gen — it's class compliant and there are no software controls.

Regards,
Geoffrey.

**Comment by duperray** [comment]
Hi @geoffreybennett ,

thanks so much for your prompt and accurate answer.
I remember now buying this second hand audio interface for not dealing at that time with any "software stack".
now that I discover all your work, I'm thinking of upgrading my setup :)

Best regards,
Pierre

**Comment by geoffreybennett** [comment]
You're welcome. I certainly think that it's fun stuff to play with!
